name: CI

on: [push]

jobs: 
  security:
  
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Terraform security scan
      uses: triat/terraform-security-scan@v3.0.0

  
